# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' unmix_c
#'
#' @param sources Data frame containing sediment source samples
#' @param samples Data frame containing mixture samples
#' @param trials Number of samples in each hypercube dimension
#' @param iter Iterations in the source variability analysis
#' @param seed Seed for the random number generator
#' @return Data frame containing the relative contribution of the sediment sources for each sediment mixture and iterations
unmix_c <- function(sources, samples, trials = 100L, iter = 100L, seed = 69512L) {
    .Call('_fingerPro_unmix_c', PACKAGE = 'fingerPro', sources, samples, trials, iter, seed)
}

#' least_squares_c
#'
#' @param sources Data frame containing sediment source samples
#' @param samples Data frame containing mixture samples
#' @param iter Iterations in the source variability analysis
#' @param seed Seed for the random number generator
#' @return Data frame containing the relative contribution solved by the least squares method
least_squares_c <- function(sources, samples, iter = 100L, seed = 69512L) {
    .Call('_fingerPro_least_squares_c', PACKAGE = 'fingerPro', sources, samples, iter, seed)
}

#' triangles_random_c
#'
#' @param sources Data frame containing sediment source samples
#' @param samples Data frame containing mixture samples
#' @param tracer Tracer in which implement the function
#' @param iter Iterations in the source variability analysis
#' @param seed Seed for the random number generator
#' @return List of data frames containing all the possible prediction for each tracer
triangles_random_c <- function(sources, samples, tracer = 0L, iter = 100L, seed = 69512L) {
    .Call('_fingerPro_triangles_random_c', PACKAGE = 'fingerPro', sources, samples, tracer, iter, seed)
}

#' triangles_virtual_c
#'
#' @param sources Data frame containing sediment source samples
#' @param samples Data frame containing mixture samples
#' @param tracer Tracer in which implement the function
#' @param iter Iterations in the source variability analysis
#' @param seed Seed for the random number generator
#' @return List of data frames containing all the possible prediction for each tracer inside the dataset
triangles_virtual_c <- function(sources, samples, tracer = 0L, iter = 100L, seed = 69512L) {
    .Call('_fingerPro_triangles_virtual_c', PACKAGE = 'fingerPro', sources, samples, tracer, iter, seed)
}

